language: java

jdk:
  - oraclejdk8

notifications:
  email:
    - rxp152830@utdallas.edu
    - txs151730@utdallas.edu
    - rxs142530@utdallas.edu
    - kxs142830@utdallas.edu

#Basic Setup and Run the build

before_install:
  - chmod +x mvnw